Add Docker deployment, update readme Docker usage
91DarioDev/forwardscoverbot pull request #36
Opened 2021-05-15 10:16 UTC by comdotwww

Have a good time!

2021-11-04 03:24 UTC, 89627039844 commented
🥰

2021-11-04 10:13 UTC, TomD420 approved these changes

2022-02-16 14:10 UTC, slvor1 requested changes
/addbuttons first link=https://telegram.org && second link same row=https://google.it &&& third link new row=https://t.me

2022-04-09 15:42 UTC, TomD420 approved these changes

2022-06-27 18:19 UTC, Dddd444hhh commented
هه

2022-06-29 19:44 UTC, closed without merging